# .github/workflows/train.yml
name: Train NN + Save Artifacts

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Download data from Google Drive
        run: |
          pip install pydrive2
          python download_data.py
        env:
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}

      - name: Run training
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python app/train.py
        env:
          EPOCHS: 50
          BATCH_SIZE: 16

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: |
            metrics.json
            metrics.png
            app/model_tf
